CREATE TABLE clientes (
  id SERIAL PRIMARY KEY UNIQUE,
  cargo VARCHAR(40) NOT NULL,
  nome VARCHAR(100) NOT NULL,
  data_nascimento DATE NOT NULL,
  salario DECIMAL NOT NULL,
  cpf VARCHAR(100) NOT NULL,
  email VARCHAR(100) NOT NULL UNIQUE,
  senha VARCHAR(100) NOT NULL
);