spring:
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME:start}
    username: ${DB_USER:start}
    password: ${DB_PASS:start}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    baseline-on-migration: true
    locations: classpath:db/migration
  cache:
    type: redis