version: '3.5'
services:
  db:
    image: postgres
    container_name: start-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=start
      - POSTGRES_PASSWORD=start
      - POSTGRES_DB=start
    volumes:
      - start-db-volume:/var/lib/postgresql/data
    restart: always
    networks:
      - startnetwork

  redis:
    image: redis:latest
    container_name: start-redis
    hostname: start-server-redis
    ports:
      - "6379:6379"
    volumes:
      - start-redis-volume:/var/lib/start-redis
    networks:
      - startnetwork

volumes:
  start-db-volume:
    driver: local
  start-redis-volume:
    driver: local

networks:
  startnetwork:
    name: startnetwork-network